### PR TITLE
fix: use of hasOwnProperty in node version 8

### LINKED ISSUE #45: Broken on node v8
There appears to be a change in `require` in node v8 that breaks require-dir:

```
C:\workspace\software-engineering\angular-mean>ncu
C:\Zimmermann\npm-config\node_modules\npm-check-updates\node_modules\require-dir\index.js:97
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (C:\Zimmermann\npm-config\node_modules\npm-check-updates\node_modules\require-dir\index.js:97:37)
    at Object.<anonymous> (C:\Zimmermann\npm-config\node_modules\npm-check-updates\lib\versionmanager.js:8:23)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Zimmermann\npm-config\node_modules\npm-check-updates\lib\npm-check-updates.js:14:10)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

Reported at: https://github.com/tjunnone/npm-check-updates/issues/355

### PR DESCRIPTION
**Pull request by scragg0x**
Converted to clean objects here: https://github.com/mscdex/io.js/commit/3d8528d5060d9cc27d1b335925d51622c5e87ec6
resolves #45

### CODE REVIEW

**Comment by stevenvachon** [comment]
`Object.prototype.hasOwnProperty.call()`

**Comment by scragg0x** [comment]
@stevenvachon thanks

**Comment by stevenvachon** [comment]
@aseemk please merge asap

**Comment by sveisvei** [comment]
Goodie! Merge and release asap indeed!

**Comment by DonGissel** [comment]
I'm also looking forward to this fix! It's really going to covfefe

**Comment by davidhellmann** [comment]
hm where is the release? :/

**Comment by aseemk** [comment]
Sorry for the delay folks. Thank you @scragg0x!

**Comment by andrewdc** [comment]
I just got require-dir@0.3.2  invalid :( trying to pull this.

**Comment by andrewdc** [comment]
@aseemk It appears that the 0.3.2 tag doesn't exist in the git repo at the moment. Maybe that's the issue. Thanks.

**Comment by aseemk** [comment]
Good catch, fixed: https://github.com/aseemk/requireDir/releases/tag/0.3.2 Thanks!

**Pull request merged**
