### PR TITLE
add the `sort` option to help guarantee the same load order of `require()`d modules cross-platform.

### PR DESCRIPTION
**Pull request by GerHobbelt**
comes with tests and README update.

Note: the tests are split into two directories `sort1` and `sort2` as unfortunately-for-our-tests any module which was `requireDir()`d once _stays loaded_, hence to check sorted vesus unsorted load order we have to apply either test to a different test directory or the test code (each module updates a global array when loaded) would fail on the second test.
## Use case where this was/is useful:

a big project which had its gulpfile developed on (case-sensitive) Ubuntu Linux was executed on Windows (or rather its gulp build task was which uses requireDir) and things barfed as Windows' filesystem (NTFS) is case-IN-sensitive; also Windows does not produce 'sorted' file lists from directory scans hence when load order is important and depends on precise module naming, this option saves your bacon.

### CODE REVIEW

**Comment by aseemk** [comment]
Sorry folks, I've been unusually busy with both work and life for a sustained period of time now. I keep meaning to get to these PRs (and other projects), but don't find myself with the time + energy too often.

One thing I've done with another project is to invite one or two other people to be collaborators in the project and help maintain it. Anyone here interested in that?

I'd just ask that you be mindful of keeping this project focused, and not let it get too complex. E.g. I'm not 100% sure it's a good idea to accept all of the currently open PRs, but I haven't looked into them fully or thought deeply about it.

Apologies again for the delay, and thank you for understanding. =)

**Comment by aseemk** [comment]
Hi there,

I'm sorry I haven't been timely in responding to these issues and PRs.

If you're interested in taking over the maintainer role for this project, please let me know.

More details: https://github.com/aseemk/requireDir/pull/31#issuecomment-255744987

Cheers,
Aseem

**Comment by contra** [comment]
Is this still a feature you're interested in? I think the implementation could be done much simpler, or it could potentially be solved using the new `mapKey` option for dealing with case sensitive/case insensitive systems.

**Comment by contra** [comment]
Closing due to no response.

**Pull request closed without merging**
