### PR TITLE
Add support for uppercase alias

### PR DESCRIPTION
**Pull request by matthoiland**
Helps to keep good case conventions when using a directory full of models or controllers. 

```
models
|-- users.js
|-- orders.js
```

``` javascript
var m = requireDir('./models', { uppercase: true });

m.Users.find({}, function(err, users){ ... });
m.Orders.find({}, function(err, orders){ ... });
```

### CODE REVIEW

**Comment by shaond** [comment]
+1

**Comment by aseemk** [comment]
Sorry folks, I've been unusually busy with both work and life for a sustained period of time now. I keep meaning to get to these PRs (and other projects), but don't find myself with the time + energy too often.

One thing I've done with another project is to invite one or two other people to be collaborators in the project and help maintain it. Anyone here interested in that?

I'd just ask that you be mindful of keeping this project focused, and not let it get too complex. E.g. I'm not 100% sure it's a good idea to accept all of the currently open PRs, but I haven't looked into them fully or thought deeply about it.

Apologies again for the delay, and thank you for understanding. =)

**Comment by blub0hr** [comment]
+1

**Comment by aseemk** [comment]
Hi there,

I'm sorry I haven't been timely in responding to these issues and PRs.

If you're interested in taking over the maintainer role for this project, please let me know.

More details: https://github.com/aseemk/requireDir/pull/31#issuecomment-255744987

Cheers,
Aseem

**Comment by gavinmcnair** [comment]
This is a great change. I made exactly the same change myself then found there was already a pull request. Can it please be committed to master.

**Comment by contra** [comment]
Hi - new maintainer here. I'd like to make a more generic `map` function to accomplish things like this, with a syntax like: `map: (f) => capitalize(f)`.

I'm going to close this PR in favor of doing that, it should be up in the next npm release.

**Pull request closed without merging**
